---
#0
- hosts: myallhosts
  vars:
    ansible_ssh_pipelining: false
    ansible_ssh_transfer_method: smart
  gather_facts: false
  become:
    true
  become_method:
    sudo
  remote_user:
    ruslan
  roles:
   - prepare

#1
- hosts: nginx
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - nginx
   - nodeexporter
  vars:
    nginx_user: www-data

#2,3
- hosts: db01 db02
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - mysql
   - nodeexporter

#4
- hosts: app
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - wordpress
   - nodeexporter

#5
- hosts: gitlab
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - update
   - gitlab
   - nodeexporter

#6
- hosts: runner
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - update
   - runner
   - nodeexporter

#7
- hosts: monitoring
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ruslan
  roles:
   - monitoring
   - nodeexporter
