version: "3.1"

volumes:
  mysql_data: {}
  mysql_backup: {}

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_backup:/var/backups/mysql_backup
    restart: always
